version: "3.9"
services:

  db:
    image: postgres:9.6.23-alpine3.14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres